### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by axewhyzed** [axewhyzed/countdown-timer-js#2]
Create documentation for the project

**Comment by b-tao** [comment]
Hello, I think I can help with this. How can I start?

**Comment by axewhyzed** [comment]
> Hello, I think I can help with this. How can I start?

All you have to do is just edit Readme.md to describe the project in the best way possible. I expected a complete beginner to show up to do it 😅 but sure you're welcome to do it. I'll now assign you to this issue.

**Comment by b-tao** [comment]
Thanks. I added some documentation to the README and created a PR for it. Hope this helps

**Comment by axewhyzed** [comment]
Great job. Thank you for contributing !
I'll close the issue once you reply.

**Comment by b-tao** [comment]
Sounds good. Glad I can help
